sonar.projectKey=anas-gn_morrocoFan30
sonar.organization=anas-gn
sonar.host.url=https://sonarcloud.io

sonar.sources=Backend/demo/src,frontend
sonar.exclusions=frontend/node_modules/**,frontend/.next/**
sonar.java.binaries=Backend/demo/target/classes