sonar.projectKey=anas-gn_morrocoFan30
sonar.organization=anas-gn
sonar.host.url=https://sonarcloud.io


sonar.sources=Backend/demo/src,Frontend
sonar.exclusions=Frontend/node_modules/**,Frontend/.next/**
sonar.java.binaries=Backend/demo/target/classes
sonar.java.libraries=Backend/demo/target/dependency/**/*.jar