#spring.datasource.url=jdbc:mysql://localhost:3306/fandb?useSSL=false&serverTim
#spring.datasource.username=root
#spring.datasource.password=

# spring.datasource.url=jdbc:mysql://sql.freedb.tech:3306/freedb_taskydb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
# spring.datasource.username=freedb_pahae
# spring.datasource.password=$YPH5fz92Mqz4Rv

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3308/fandb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Server Configuration
server.port=3309
server.servlet.session.timeout=30m
server.servlet.session.cookie.max-age=1800
server.servlet.session.cookie.http-only=true
server.servlet.session.tracking-modes=cookie

# PDF Monkey
pdfmonkey.api.key=QyKRWXDEa-bVxK7ynjzv
pdfmonkey.template.id=F88D4427-D2B0-4245-8AC1-79C717ABEA78

# WebSocket
spring.websocket.stomp.enabled=true

# Logging
logging.level.org.springframework.messaging=DEBUG
logging.level.org.springframework.web.socket=DEBUG

# Security (temporary for dev)
spring.security.user.name=user
spring.security.user.password=password