name: Deploy Backend to HuggingFace

on:
  push:
    branches:
      - main
    paths:
      - 'Backend/demo/**'
      - 'Frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout MORROCOFAN30
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: |
          cd Backend/demo
          mvn clean package -DskipTests

      - name: Install Sonar Scanner
        run: npm install -g sonar-scanner

      - name: SonarQube Analysis (Backend + Frontend)
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.token=$SONAR_TOKEN

      - name: Push Backend to HuggingFace Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git clone https://Anas-gana1:$HF_TOKEN@huggingface.co/spaces/Anas-gana1/fandb-backend hf-repo
          cp -r Backend/demo/src hf-repo/
          cp Backend/demo/pom.xml hf-repo/
          cp Backend/demo/Dockerfile hf-repo/
          cd hf-repo
          git add .
          git diff --staged --quiet || git commit -m "sync from GitHub - $GITHUB_SHA"
          git push